name: Logan James
favicon: null
layout_spectrum: 0.2961514771450311
typography_spectrum: 0.16533379000611603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.125
  lightness: 0.5028805625624955
  saturation: 0.8919699592515826
  rhythmicContrast: 0.03851290140300989
purpose: []
